version: "2"

networks:
  net:

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    hostname: prometheus
    restart: always
    tty: true
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9091:9090

    networks:
      - net

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    hostname: grafana
    environment:
      - GF_AUTH_PROXY_ENABLED=true
      - GF_PATHS_PROVISIONING=/var/lib/grafana/provisioning/
    volumes:
      - ./provisioning/:/var/lib/grafana/provisioning/
      - ./grafana.ini:/etc/grafana/grafana.ini
    ports:
      - 9092:3000
    networks:
      - net
    depends_on:
      - prometheus
  cad:
    image: gcr.io/cadvisor/cadvisor
    container_name: cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - 9093:8080
    restart: always
    networks:
      - net
    deploy:
      mode: global

	blackbox:
    image: prom/blackbox-exporter:v0.16.0
    container_name: blackbox
    restart: unless-stopped
    command:
      - "--config.file=/etc/blackbox/blackbox.yml"
    networks:
      - net
    volumes:
      - ./config/blackbox.yml:/etc/blackbox/blackbox.yml
