global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.

alerting:
  alertmanagers:
    - static_configs:
        - targets:
rule_files:
scrape_configs:


  - job_name: 'node_exporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.2.199:9100']
        labels:
          instance: 'Desktop'
      - targets: ['192.168.2.200:9100']
        labels:
          instance: 'Laptop'


  - job_name: 'docker'
    static_configs:
      - targets:
        - localhost:9093



  - job_name: 'cadvisor'
    scrape_interval: 10s 
    static_configs:
      - targets: 
        - 192.168.2.199:8080
        labels:
          Node: 'Desktop'


  - job_name: 'blackbox'
    scrape_interval: 10s
    metrics_path: /probe
    static_configs:
      - targets:
        - https://pro-admin.mybiz.com.vn
        - https://viblo.asia
        - https://npm.mybiz.com.vn
        - https://npm.zackcloud.tk
        - https://monit.zackcloud.tk
        - https://proxmox.zackcloud.tk
    params:
      module: [http_2xx]
    relabel_configs:
      - source_labels: [ __address__ ]
        target_label: __param_target
      - source_labels: [ __param_target ]
        target_label: instance
      - target_label: __address__
        replacement: "192.168.2.199:9115"
