version: '3.7'
networks: 
  net:
services:
  cad:
    image: gcr.io/cadvisor/cadvisor
    container_name: cad
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - 8080:8080
    restart: always
    networks: 
      - net
    deploy:
      mode: global
  
