version: "3"
services:
  filebrowser:
    image: filebrowser/filebrowser
    container_name: file-browser
    user: 1000:1000 
    ports:
      - 9009:80
    volumes:
      - /home/zack:/srv
      - /home/zack/Documents/file-browser/filebrowser.db:/database.db
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
